src/accounts/urls.py
from django.urls import path
from .views import logged_out_view, register_view, profile_view, profile_edit_view, change_pw_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page="/accounts/logged_out_success"), name="logout"),
    path('logged_out_success/', logged_out_view, name='logged_out'),
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', profile_edit_view, name='profile_edit'),
    path('change_password/', change_pw_view, name='change_password'),
]

src/item/urls.py
from django.urls import path
from .views import (
    show_item_view,
    register_item_view,
    search_item_view
)

app_name = "items"
urlpatterns = [
    path('register/', register_item_view, name="register_item"),
    path('item/<int:item_id>/', show_item_view, name="show_item"),
    path('search/', search_item_view, name="search_item"),
]

src/lost_found/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from pages.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='account_home'),
    path('items/', include('item.urls'), name='item_home'),
    path('', home_view, name="home")
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/templates/pages/base.html
{% load staticfiles %}

<!doctype html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
        

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block title-block %}
        <title>Lost & Found</title>
        {% endblock title-block %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand">Lost & Found</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url "home"%}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'items:register_item'%}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'items:search_item'%}">Search</a>
                </div>
                <div class="navbar-nav w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-secondary btn-sm active" style="margin:2px" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-danger btn-sm active" style="margin:2px" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-primary btn-sm active" style="margin:2px" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    {% endif %}
                    </li>
                    </ul>
                </div>
            </div>
            </nav>
        </header>
        <main role='main'>
        <section class="jumbotron text-center" style="padding:10px">
            <div class="container">
                {% block head-block %}
                {% endblock head-block %}
            </div>
        </section>
        <div class='container'>
            {% block content-block %}
            {% endblock content-block %}

            {% block search-result-block %}
            {% endblock search-result-block %}
        </div>
        </main>
    </body>
</html>

src/pages/templates/pages/home.html
{% extends 'pages/base.html'%}

{% block head-block %}
<div class="container">
<h1>Never Miss a Thing</h1>
</div>
{% endblock head-block %}

{% block content-block %}
<div class='container'>
<h1 class="jumbotron-heading">Welcome, {{ user.username }}<h1>
<p class="lead text-muted">
Clicking following buttons to either <strong>Register</strong> an item or <strong>Search</strong> for an item
</p>
<a href="{% url 'items:register_item'%}" class="btn btn-primary btn-lg my-2">Register</a>
<a href="{% url 'items:search_item'%}" class="btn btn-primary btn-lg my-2">Search</a>
</div>
{% endblock content-block %}