src/accounts/urls.py
from django.urls import path
from .views import logged_out_view, register_view, profile_view, profile_edit_view, change_pw_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page="/accounts/logged_out_success"), name="logout"),
    path('logged_out_success/', logged_out_view, name='logged_out'),
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', profile_edit_view, name='profile_edit'),
    path('change_password/', change_pw_view, name='change_password'),
]

src/item/urls.py
from django.urls import path
from .views import (
    show_item_view,
    register_item_view,
    search_item_view
)

app_name = "items"
urlpatterns = [
    path('register/', register_item_view, name="register_item"),
    path('item/<int:item_id>/', show_item_view, name="show_item"),
    path('search/', search_item_view, name="search_item"),
]

src/lost_found/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from pages.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='account_home'),
    path('items/', include('item.urls'), name='item_home'),
    path('', home_view, name="home")
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    employeeID = models.CharField(max_length=10, blank=False,null=False)
    phone = models.CharField(max_length=12, blank=True, null=True)
    
    objects = models.Manager()

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from profiles.models import Profile

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=20,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    email = forms.EmailField(required=False,
        widget=forms.TextInput(
            attrs={
                'class':"form-control",
                'size':30
            }
        )
    )
    first_name = forms.CharField(max_length=20,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    last_name = forms.CharField(max_length=20,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'email',
        ]
        
    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

class UserEditForm(UserChangeForm):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class':"form-control",
                'size':30
            }
        )
    )
    first_name = forms.CharField(max_length=20,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    last_name = forms.CharField(max_length=20,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]
    

src/profiles/forms.py
from django import forms
from .models import Profile

class UserProfileForm(forms.ModelForm):
    phone = forms.CharField(max_length=20, required=False,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    employeeID = forms.CharField(max_length=10,
        widget=forms.TextInput(
            attrs={
                'class':"form-control",
                'size':10
            }
        )
    )
    class Meta:
        model = Profile
        fields = [
            'employeeID',
            'phone',
        ]

class ProfileEditForm(forms.ModelForm):
    phone = forms.CharField(max_length=20, required=False,
        widget=forms.TextInput(
            attrs={
                'class':"form-control"
            }
        )
    )
    class Meta:
        model =Profile
        fields = [
            'phone',
        ]

src/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import UserRegisterForm, UserEditForm
from profiles.forms import UserProfileForm, ProfileEditForm
from django.contrib.auth import authenticate, login, update_session_auth_hash
from profiles.models import Profile
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def logged_out_view(request):
    return render(request, 'accounts/logged_out.html')

def register_view(request):
    if request.method == 'POST':
        register_form  = UserRegisterForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if register_form.is_valid() and profile_form.is_valid():
            user = register_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save( )

            username = register_form.cleaned_data.get('username')
            raw_password = register_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:base')
    else:
        register_form = UserRegisterForm()
        profile_form = UserProfileForm()
    context = {
        'register_form':register_form,
        'profile_form':profile_form    
    }
    return render(request, 'accounts/register.html', context)

@login_required
def profile_view(request):
    context = {
        'user': request.user,
        'profile': Profile.objects.get(user__id=request.user.pk)
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def profile_edit_view(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, instance=Profile.objects.get(user__id=request.user.pk))
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('accounts:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=Profile.objects.get(user__id=request.user.pk))
        context = {
            'user_form': user_form,
            'profile_form': profile_form,
            'profile':Profile.objects.get(user__id=request.user.pk)
        }
        return render(request, "accounts/profile_edit.html", context)

@login_required
def change_pw_view(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change_password')
    else:
        form = PasswordChangeForm(request.user)
        context = {
            'form': form,
        }
        return render(request, "accounts/change_password.html", context)

src/profiles/views.py
from django.shortcuts import render

# Create your views here.

src/accounts/templates/accounts/change_password.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Profile Edit</title>
{% endblock title-block %}

{% block head-block %}
<h1>Change Password</h1>
{% endblock head-block %}

{% block content-block %}
<div>
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{% url 'accounts:profile'%}" class="btn btn-primary my-2">Cancel</a>
</form>
<br>
</div>
{% endblock content-block %}

src/accounts/templates/accounts/logged_out.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Logout Success</title>
{% endblock title-block %}

{% block head-block %}
<h1>You have logged out</h1>
{% endblock head-block %}

{% block content-block %}
<div>
    <a href="{% url 'accounts:login'%}">Login again</a> 
</div>
{% endblock content-block %}

src/accounts/templates/accounts/login.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Login</title>
{% endblock title-block %}

{% block head-block %}
<h1>Login</h1>
{% endblock head-block %}

{% block content-block %}
<div>
    <form method="POST" class="form-signin"> {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Please Signin</h1>
        {{ form.username.label_tag }}
        {{ form.username }} <br>
        {{ form.password.label_tag }}
        {{ form.password }}<br>
        <button type='submit' class="btn btn-lg btn-primary btn-block" style="width:100px">Sign in</button>
    </form>
    <p>Dont have an account? <a href="/accounts/register">Register</a></p>
    
</div>
{% endblock content-block %}

src/accounts/templates/accounts/logout.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Logout</title>
{% endblock title-block %}

{% block head-block %}
<h1>Logout</h1>
{% endblock head-block %}

{% block content-block %}
<div>
    <p>You have logged out</p>
    <a href="{% url 'accounts:login' %}">Login again</a>
</div>
{% endblock content-block %}

src/accounts/templates/accounts/profile.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Profile</title>
{% endblock title-block %}

{% block head-block %}
<h1>Profile</h1>
{% endblock head-block %}

{% block content-block %}
<div>
    <p>User Name: {{ user.username }}</p>
    <p>Employee ID: <strong>{{ profile.employeeID }}</strong></p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Phone: {% if profile.phone is not None %} 
                {{ profile.phone }} 
              {% else %} 
                None 
              {% endif %}</p>
</div>
<div>
  <a href="{% url 'accounts:profile_edit' %}" class="btn btn-primary my-2">Edit Profile</a>
  <a href="{% url 'accounts:change_password'%}" class="btn btn-secondary my-2">Change Password</a> 
</div>
{% endblock content-block %}

src/accounts/templates/accounts/profile_edit.html
{% extends 'pages/base.html' %}

{% block title-block %}
<title>Profile Edit</title>
{% endblock title-block %}

{% block head-block %}
<h1>Profile Edit</h1>
{% endblock head-block %}

{% block content-block %}
<div>
<form method="POST"> {% csrf_token %}
    {{ user_form.non_field_errors }}
    {{ profile_form.non_field_errors }}
    <p>
    {{ user_form.first_name.errors }}
    <label for="{{ user_form.first_name.id_for_label }}">First name: </label>
    {{ user_form.first_name }}
    </p>
    <p>
    Employee ID: <strong>{{ profile.employeeID }}</strong>
    </p>
    <p>
    {{ user_form.last_name.errors }}
    <label for="{{ user_form.last_name.id_for_label }}">Last name: </label>
    {{ user_form.last_name }}
    </p>
    <p>
    {{ user_form.email.errors }}
    <label for="{{ user_form.email.id_for_label }}">Email: </label>
    {{ user_form.email }}
    </p>
    <p>
    {{ profile_form.phone.errors }}
    <label for="{{ profile_form.phone.id_for_label }}">Phone: </label>
    {{ profile_form.phone }}
    </p>

    <button type="submit" class="btn btn-primary">Save</button>
    <a href="../" class="btn btn-primary my-2">Cancel</a>
</form>
<br>
</div>
{% endblock content-block %}

src/accounts/templates/accounts/register.html
{% extends 'pages/base.html' %}

{% block titl-block %}
<title>Register</title>
{% endblock %}

{% block head-block %}
<div>
<h1>Register New Account</h1>
</div>
{% endblock %}



{% block content-block %}
<div class="container">
    <form method='POST'>    {% csrf_token %}
        {{ register_form.non_field_errors }}
        {{ profile_form.non_field_errors }}
        <p>
        {{ register_form.username.errors }}
        <label for="{{ register_form.username.id_for_label }}">User Name: </label>
        {{ register_form.username }}
        </p>
        <p>
        {{ profile_form.employeeID.errors }}
        <label for="{{ profile_form.employeeID.id_for_label }}">Employee ID: </label>
        {{ profile_form.employeeID }}
        </p>
        <p>
        {{ register_form.password1.errors }}
        <label for="{{ register_form.password1.id_for_label }}">Password: </label>
        {{ register_form.password1 }}
        </p>
        <p>
        {{ register_form.password2.errors }}
        <label for="{{ register_form.password2.id_for_label }}">Password Confirm: </label>
        {{ register_form.password2 }}
        </p>
        <p>
        {{ register_form.first_name.errors }}
        <label for="{{ register_form.first_name.id_for_label }}">First Name: </label>
        {{ register_form.first_name }}
        </p>
        <p>
        {{ register_form.last_name.errors }}
        <label for="{{ register_form.last_name.id_for_label }}">Last Name: </label>
        {{ register_form.last_name }}
        </p>
        <p>
        {{ register_form.email.errors }}
        <label for="{{ register_form.email.id_for_label }}">Email Address: </label>
        {{ register_form.email }}
        </p>
        <p>
        {{ profile_form.phone.errors }}
        <label for="{{ profile_form.phone.id_for_label }}">Phone Number: </label>
        {{ profile_form.phone }}
        </p>
        <input type="submit" value="Register" >
    </form>
</div>
{% endblock content-block %}